import type { Metadata } from "next"
import { ProductDetail } from "@/components/product-detail"

export const metadata: Metadata = {
  title: "Palestine Heel Kuffiyeh AF1 - Soul Purpose Footwear",
  description:
    "White Nike Air Force 1 with Palestinian flag design on heel and traditional Kuffiyeh patterns. Hand-painted with premium materials.",
}

const shoe = {
  id: 12,
  name: "Palestine Heel Kuffiyeh AF1",
  price: 160,
  images: ["/images/palestine-heel-af1-side.jpeg", "/images/palestine-heel-af1-back.jpeg"],
  description: "White Nike Air Force 1 with Palestinian flag design on heel and traditional Kuffiyeh patterns.",
  details: [
    "Hand-painted Palestinian flag on heel",
    "Traditional Kuffiyeh geometric patterns",
    "Premium white leather base",
    "Palestinian flag colors on Nike AIR branding",
    "Sticker price: $160",
  ],
  sizes: [
    "7",
    "7.5",
    "8",
    "8.5",
    "9",
    "9.5",
    "10",
    "10.5",
    "11",
    "11.5",
    "12",
    "12.5",
    "13",
    "13.5",
    "14",
    "14.5",
    "15",
    "5W",
    "5.5W",
    "6W",
    "6.5W",
    "7W",
    "7.5W",
    "8W",
    "8.5W",
    "9W",
    "9.5W",
    "10W",
    "10.5W",
    "11W",
    "11.5W",
    "12W",
    "1C",
    "1.5C",
    "2C",
    "2.5C",
    "3C",
    "3.5C",
    "4C",
    "4.5C",
    "5C",
    "5.5C",
    "6C",
    "6.5C",
    "7C",
    "7.5C",
    "8C",
    "8.5C",
    "9C",
    "9.5C",
    "10C",
    "10.5C",
    "11C",
    "11.5C",
    "12C",
    "12.5C",
    "13C",
    "13.5C",
    "1Y",
    "1.5Y",
    "2Y",
    "2.5Y",
    "3Y",
    "3.5Y",
    "4Y",
    "4.5Y",
    "5Y",
    "5.5Y",
    "6Y",
    "6.5Y",
    "7Y",
    "7.5Y",
    "8Y",
  ],
  slug: "palestine-heel-kuffiyeh-af1",
  isFeatured: true,
}

export default function PalestineHeelKuffiyehAF1Page() {
  return <ProductDetail shoe={shoe} />
}
